# Generated by Django 3.2.15 on 2022-10-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.AddField(
            model_name='todo',
            name='due_time',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
